import { Category, Product, RequestForQuote, Quote, Inquiry, User } from "./types";

export const categories: Category[] = [
  {
    id: "cat-1",
    name: "Fruits",
    description: "Fresh and organic fruits – seasonal & tropical",
    slug: "fruits",
    image: "https://images.unsplash.com/photo-1557844352-757b2a80ead6?w=500&h=300&fit=crop",
    isFeatured: true,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "cat-2",
    name: "Vegetables",
    description: "Fresh vegetables, premium quality, pesticide-free",
    slug: "vegetables",
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=500&h=300&fit=crop",
    isFeatured: true,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "cat-3",
    name: "Dairy",
    description: "Fresh dairy products and alternatives",
    slug: "dairy",
    image: "https://images.unsplash.com/photo-1628185286662-d6ad82d4d339?w=500&h=300&fit=crop",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "cat-4",
    name: "Grains & Cereals",
    description: "Bulk grains and cereal products",
    slug: "grains-cereals",
    image: "https://images.unsplash.com/photo-1574521521267-e686baa91713?w=500&h=300&fit=crop",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "cat-5",
    name: "Halal Meat & Proteins",
    description: "Halal-certified meat, fish, and protein",
    slug: "proteins",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=300&fit=crop",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
];

export const products: Product[] = [
  {
    id: "prod-1",
    name: "Organic Apples",
    description: "Fresh, crisp organic apples from local orchards. Perfect for retail or food service.",
    category: categories[0],
    categoryId: "cat-1",
    price: 45.99,
    unit: "kg",
    minOrderQuantity: 50,
    stock: 500,
    image: "https://images.unsplash.com/photo-1619546813926-a78fa6372cd2?w=500&h=300&fit=crop",
    sku: "APPLE-001",
    certifications: ["Organic", "Fair Trade"],
    origin: "Local Orchards",
    shelf_life_days: 21,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "prod-2",
    name: "Banana Bunches",
    description: "Golden ripe bananas, ideal for retail distribution and food processing.",
    category: categories[0],
    categoryId: "cat-1",
    price: 32.5,
    unit: "kg",
    minOrderQuantity: 100,
    stock: 800,
    image: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=500&h=300&fit=crop",
    sku: "BANANA-001",
    certifications: ["Organic"],
    origin: "Tropical Region",
    shelf_life_days: 14,
    createdAt: new Date("2024-01-16"),
    updatedAt: new Date("2024-01-16"),
  },
  {
    id: "prod-3",
    name: "Leafy Greens Mix",
    description: "Mixed fresh greens including spinach, lettuce, and kale. Pre-washed and ready.",
    category: categories[1],
    categoryId: "cat-2",
    price: 55.0,
    unit: "kg",
    minOrderQuantity: 25,
    stock: 300,
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4994?w=500&h=300&fit=crop",
    sku: "GREENS-001",
    certifications: ["Organic", "Pesticide-Free"],
    origin: "Local Farms",
    shelf_life_days: 7,
    createdAt: new Date("2024-01-16"),
    updatedAt: new Date("2024-01-16"),
  },
  {
    id: "prod-4",
    name: "Tomatoes (Vine)",
    description: "Ripe vine tomatoes with excellent flavor profile and color.",
    category: categories[1],
    categoryId: "cat-2",
    price: 48.75,
    unit: "kg",
    minOrderQuantity: 50,
    stock: 400,
    image: "https://images.unsplash.com/photo-1546470427-3f2d26d22d2d?w=500&h=300&fit=crop",
    sku: "TOMATO-001",
    certifications: ["Organic"],
    origin: "Local Farms",
    shelf_life_days: 10,
    createdAt: new Date("2024-01-17"),
    updatedAt: new Date("2024-01-17"),
  },
  {
    id: "prod-5",
    name: "Whole Milk",
    description: "Fresh, pasteurized whole milk from local dairy farms.",
    category: categories[2],
    categoryId: "cat-3",
    price: 18.5,
    unit: "L",
    minOrderQuantity: 100,
    stock: 1000,
    image: "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=500&h=300&fit=crop",
    sku: "MILK-001",
    certifications: ["Pasteurized"],
    origin: "Local Dairy",
    shelf_life_days: 14,
    createdAt: new Date("2024-01-17"),
    updatedAt: new Date("2024-01-17"),
  },
  {
    id: "prod-6",
    name: "Yogurt (Plain)",
    description: "Natural yogurt with live cultures, no added sugars.",
    category: categories[2],
    categoryId: "cat-3",
    price: 42.0,
    unit: "kg",
    minOrderQuantity: 30,
    stock: 250,
    image: "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=500&h=300&fit=crop",
    sku: "YOGURT-001",
    certifications: ["Probiotic"],
    origin: "Local Dairy",
    shelf_life_days: 21,
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "prod-7",
    name: "Brown Rice",
    description: "Long-grain brown rice, nutrient-rich and versatile.",
    category: categories[3],
    categoryId: "cat-4",
    price: 28.5,
    unit: "kg",
    minOrderQuantity: 100,
    stock: 1500,
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&h=300&fit=crop",
    sku: "RICE-001",
    certifications: ["Organic", "Non-GMO"],
    origin: "Agricultural Region",
    shelf_life_days: 365,
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "prod-8",
    name: "Wheat Flour",
    description: "Premium whole wheat flour for baking and cooking.",
    category: categories[3],
    categoryId: "cat-4",
    price: 15.75,
    unit: "kg",
    minOrderQuantity: 200,
    stock: 2000,
    image: "https://images.unsplash.com/photo-1574323347407-f5e1c4e2b4a0?w=500&h=300&fit=crop",
    sku: "FLOUR-001",
    certifications: ["Organic"],
    origin: "Grain Mills",
    shelf_life_days: 180,
    createdAt: new Date("2024-01-19"),
    updatedAt: new Date("2024-01-19"),
  },
  {
    id: "prod-9",
    name: "Fresh Chicken Breast",
    description: "Halal-certified, boneless chicken breast from free-range farms.",
    category: categories[4],
    categoryId: "cat-5",
    price: 125.0,
    unit: "kg",
    minOrderQuantity: 10,
    stock: 150,
    image: "https://images.unsplash.com/photo-1604503468506-6f987258b8d?w=500&h=300&fit=crop",
    sku: "CHICKEN-001",
    certifications: ["Halal", "Free-Range"],
    origin: "Local Farm",
    shelf_life_days: 3,
    createdAt: new Date("2024-01-19"),
    updatedAt: new Date("2024-01-19"),
  },
  {
    id: "prod-10",
    name: "Salmon Fillets",
    description: "Wild-caught salmon fillets, fresh and premium quality.",
    category: categories[4],
    categoryId: "cat-5",
    price: 180.0,
    unit: "kg",
    minOrderQuantity: 5,
    stock: 80,
    image: "https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?w=500&h=300&fit=crop",
    sku: "SALMON-001",
    certifications: ["Wild-Caught", "Sustainable"],
    origin: "Cold Waters",
    shelf_life_days: 2,
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
];

export const requestsForQuote: RequestForQuote[] = [
  {
    id: "rfq-1",
    userId: "user-1",
    items: [
      { productId: "prod-1", quantity: 100, unit: "kg" },
      { productId: "prod-3", quantity: 50, unit: "kg" },
    ],
    companyName: "Fresh Foods Market",
    contactPerson: "John Smith",
    email: "john@freshfoods.com",
    phone: "+1-555-0101",
    deliveryAddress: "123 Market Street, City, State 12345",
    status: "pending",
    notes: "Need for grand opening. Urgent delivery required.",
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-02-15"),
  },
  {
    id: "rfq-2",
    userId: "user-2",
    items: [
      { productId: "prod-5", quantity: 200, unit: "L" },
      { productId: "prod-6", quantity: 150, unit: "kg" },
    ],
    companyName: "Organic Café Chain",
    contactPerson: "Sarah Johnson",
    email: "sarah@organiccafe.com",
    phone: "+1-555-0102",
    deliveryAddress: "456 Health Avenue, City, State 67890",
    status: "reviewed",
    notes: "Regular monthly orders. Looking for consistent supply.",
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-02-16"),
  },
  {
    id: "rfq-3",
    userId: "user-3",
    items: [
      { productId: "prod-7", quantity: 500, unit: "kg" },
      { productId: "prod-8", quantity: 300, unit: "kg" },
    ],
    companyName: "Artisan Bakery Co",
    contactPerson: "Mike Brown",
    email: "mike@artisanbakery.com",
    phone: "+1-555-0103",
    deliveryAddress: "789 Baker Lane, City, State 34567",
    status: "quoted",
    notes: "Bulk order for new production line.",
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-02-14"),
  },
];

export const quotes: Quote[] = [
  {
    id: "quote-1",
    rfqId: "rfq-3",
    items: [
      {
        productId: "prod-7",
        quantity: 500,
        unit: "kg",
        unitPrice: 28.5,
        totalPrice: 14250,
      },
      {
        productId: "prod-8",
        quantity: 300,
        unit: "kg",
        unitPrice: 15.75,
        totalPrice: 4725,
      },
    ],
    totalPrice: 18975,
    validUntil: new Date("2024-03-05"),
    status: "sent",
    createdAt: new Date("2024-02-14"),
    updatedAt: new Date("2024-02-14"),
  },
];

export const inquiries: Inquiry[] = [
  {
    id: "inq-1",
    name: "Emma Davis",
    email: "emma@example.com",
    phone: "+1-555-0201",
    subject: "Product Quality Certification",
    message:
      "Hi, I'd like to know more about your organic certification process for the vegetables.",
    status: "new",
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-02-20"),
  },
  {
    id: "inq-2",
    name: "Robert Wilson",
    email: "robert@example.com",
    phone: "+1-555-0202",
    subject: "Bulk Order Discount",
    message: "Are there discounts available for orders over 1000kg?",
    status: "read",
    createdAt: new Date("2024-02-18"),
    updatedAt: new Date("2024-02-19"),
  },
  {
    id: "inq-3",
    name: "Lisa Anderson",
    email: "lisa@example.com",
    phone: "+1-555-0203",
    subject: "Delivery Options",
    message:
      "What are your delivery options and timeframes for the northern region?",
    status: "replied",
    createdAt: new Date("2024-02-16"),
    updatedAt: new Date("2024-02-17"),
  },
];

export const mockUsers: User[] = [
  {
    id: "user-admin",
    email: "admin@wholegrains.com",
    name: "Admin User",
    role: "admin",
    company: "Whole Grains Co",
    phone: "+1-555-0001",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "user-1",
    email: "john@freshfoods.com",
    name: "John Smith",
    role: "customer",
    company: "Fresh Foods Market",
    phone: "+1-555-0101",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "user-2",
    email: "sarah@organiccafe.com",
    name: "Sarah Johnson",
    role: "customer",
    company: "Organic Café Chain",
    phone: "+1-555-0102",
    createdAt: new Date("2024-01-16"),
    updatedAt: new Date("2024-01-16"),
  },
  {
    id: "user-3",
    email: "mike@artisanbakery.com",
    name: "Mike Brown",
    role: "customer",
    company: "Artisan Bakery Co",
    phone: "+1-555-0103",
    createdAt: new Date("2024-01-17"),
    updatedAt: new Date("2024-01-17"),
  },
];

// Helper functions
export const getCategoryById = (id: string) =>
  categories.find((c) => c.id === id);

export const getProductsByCategory = (categoryId: string) =>
  products.filter((p) => p.categoryId === categoryId);

export const getProductById = (id: string) =>
  products.find((p) => p.id === id);

export const getRFQById = (id: string) =>
  requestsForQuote.find((r) => r.id === id);

export const getQuoteByRFQId = (rfqId: string) =>
  quotes.find((q) => q.rfqId === rfqId);

export const getInquiryById = (id: string) =>
  inquiries.find((i) => i.id === id);
